export const Buttons = [
    { name: "minusButton", source: "assets/img/Minus-Button.png", pressed: false },
    { name: "plusButton", source: "assets/img/Plus-Button.png", pressed: false },
    { name: "cancelButton", source: "assets/img/Button-175.png", pressed: false },
    { name: "purchaseButton", source: "assets/img/Button-225.png", pressed: false },
    { name: "zeroButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "oneButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "twoButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "threeButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "fourButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "fiveButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "sixButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "sevenButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "eightButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "nineButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "aButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "bButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "cButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "dButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "eButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "fButton", source: "assets/img/Button-60.png", pressed: false },
    { name: "deleteButton", source: "assets/img/Button-312.png", pressed: false },
    { name: "enterButton", source: "assets/img/Button-312.png", pressed: false },
    { name: "loginBackButton", source: "assets/img/Button-175.png", pressed: false },
    { name: "pastInfoButton", source: "assets/img/Button-225.png", pressed: false },
    { name: "pastInfoBackButton", source: "assets/img/Button-175.png", pressed: false },
    { name: "continueButton", source: "assets/img/Button-225.png", pressed: false }
];
