CC = gcc
CFlags = -Wall -pedantic -std=c11

clean:
	rm -rf *.sh


run:
	./endWindowManager.sh
	./removeCompizRestrictions.sh
	./disableFirefoxAddons.sh
	./removeFirefoxRestrictions.sh
	./endEmptyTrash.sh
	
	
	
