CC = gcc
CFlags = -Wall -pedantic -std=c11

#all: foutputTest.o foutputTest2.o foutput.o wline.o
	#${CC} -o foutputTest foutputTest.o foutput.o wline.o

run: 
	./set_xinput_matrix.sh


#build: clean foutput.o
	#cp foutput.o ../../build

build:
	cp set_xinput_matrix.sh ../../build/setup/start;


