CC = gcc
CFlags = -Wall -pedantic -std=c11

clean:
	rm -rf *.sh


run1:
	./set_xinput_matrix.sh
	./addFirefoxRestrictions.sh
	./enableFirefoxAddons.sh
	./startEmptyTrash.sh
	./addCompizRestrictions.sh

run2:
	./setWindowSizes.sh
	./startWindowManager.sh
