run:
	## Make sure to start firefox and run the add ins
	## then run start shell scripts and restart firefox
	(cd "setup"; make run1;)
	(cd "vending-app"; npm start;)
	(cd "setup"; make run2;)

stop:
	(cd "setup"; make stop;)